name: CD with Versioning
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ] 

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Calculate Metadata
        id: meta
        run: |
          echo "TS=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV
          
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build and push
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/python-app
          
          # Budujemy i tagujemy datą oraz wersją 
          docker build . \
            -t $IMAGE_NAME:${{ env.TS }} \
            -t $IMAGE_NAME:${{ env.VERSION }}
          
          # Wypychamy oba tagi
          docker push $IMAGE_NAME:${{ env.TS }}
          docker push $IMAGE_NAME:${{ env.VERSION }}