name: CD GHCR
on:
  push:
    branches: [ main ]
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    permissions: 
      packages: write # Ważne: to pozwala GitHubowi zapisać obraz w rejestrze
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build and push
        # Uwaga: zmienia nazwę obrazu na małe litery, bo Docker tego wymaga
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER_LC/python-app:latest .
          docker push ghcr.io/$OWNER_LC/python-app:latest